package View;

import Entity.Book;
import Entity.CallCard;
import Entity.User;
import Form.FilterForm;
import java.time.LocalDate;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Admin
 */
public class CreateCallCard extends javax.swing.JFrame {

    /**
     * Creates new form CreateCallCard
     */
    HomeLibrarian homeLibrarian;
    List<User> userList;
    List<Book> bookList;
    FilterForm filterUser;
    FilterForm filterBook;
    
    
    public CreateCallCard(HomeLibrarian homeLibrarian) {
        this.homeLibrarian = homeLibrarian;
        filterUser = new FilterForm();
        filterBook = new FilterForm();
        initComponents();
        resetTableBooks(filterBook);
        resetTableUsers(filterUser);
        borrowedDate.setDate(new Date());
    }
    
    public CreateCallCard() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableUser = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableBook = new javax.swing.JTable();
        inputSearchUser = new javax.swing.JTextField();
        sreachUserBtn = new javax.swing.JButton();
        inputSearchBook = new javax.swing.JTextField();
        searchBookBtn = new javax.swing.JButton();
        chooserBook = new javax.swing.JButton();
        chooseUser = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        libraryCard = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        bookId = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        borrowedDate = new com.toedter.calendar.JDateChooser();
        confirm = new javax.swing.JButton();
        exit = new javax.swing.JButton();
        mess = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(230, 226, 238));

        tableUser.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tableUser.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Thẻ thư viện", "Tên Độc Giả", "Giới tính", "Quê Quán"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tableUser.setIntercellSpacing(new java.awt.Dimension(5, 5));
        tableUser.setRowHeight(30);
        jScrollPane1.setViewportView(tableUser);

        tableBook.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tableBook.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã Sách", "Tên Sách", "Nhà Xuất Bản", "Năm Xuất Bản"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tableBook.setIntercellSpacing(new java.awt.Dimension(5, 5));
        tableBook.setRowHeight(30);
        jScrollPane2.setViewportView(tableBook);

        sreachUserBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        sreachUserBtn.setText("Tìm kiếm");
        sreachUserBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sreachUserBtnMouseClicked(evt);
            }
        });

        searchBookBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        searchBookBtn.setText("Tìm kiếm");
        searchBookBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchBookBtnMouseClicked(evt);
            }
        });

        chooserBook.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        chooserBook.setText("Chọn");
        chooserBook.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                chooserBookMouseClicked(evt);
            }
        });

        chooseUser.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        chooseUser.setText("Chọn");
        chooseUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                chooseUserMouseClicked(evt);
            }
        });
        chooseUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chooseUserActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setText("Thẻ thư viện");

        libraryCard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                libraryCardActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setText("Mã Sách");

        bookId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookIdActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setText("Ngày mượn");

        confirm.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        confirm.setText("Xác nhận");
        confirm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                confirmMouseClicked(evt);
            }
        });

        exit.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        exit.setText("Thoát");

        mess.setFont(new java.awt.Font("Times New Roman", 3, 15)); // NOI18N
        mess.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(inputSearchUser, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(sreachUserBtn)
                                .addGap(18, 18, 18)
                                .addComponent(chooseUser)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(inputSearchBook, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(searchBookBtn)
                                .addGap(18, 18, 18)
                                .addComponent(chooserBook)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(326, 326, 326)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(confirm, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)
                                .addComponent(exit, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(24, 24, 24)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(libraryCard)
                                    .addComponent(bookId, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                                    .addComponent(borrowedDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(392, 392, 392)
                .addComponent(mess, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(inputSearchUser)
                        .addComponent(chooseUser, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(sreachUserBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(inputSearchBook)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(searchBookBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(chooserBook, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(62, 62, 62)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(libraryCard, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bookId, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(borrowedDate, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(mess, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(confirm, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                    .addComponent(exit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(62, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void chooseUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chooseUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chooseUserActionPerformed

    private void bookIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bookIdActionPerformed

    private void libraryCardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_libraryCardActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_libraryCardActionPerformed

    private void sreachUserBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sreachUserBtnMouseClicked
        // TODO add your handling code here:
        filterUser.setTypeSearch("fullname");
        filterUser.setSearch(inputSearchUser.getText());
        resetTableUsers(filterUser);
    }//GEN-LAST:event_sreachUserBtnMouseClicked

    private void searchBookBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchBookBtnMouseClicked
        // TODO add your handling code here:
        filterBook.setTypeSearch("name");
        filterBook.setSearch(inputSearchBook.getText());
        resetTableBooks(filterBook);
    }//GEN-LAST:event_searchBookBtnMouseClicked

    private void chooseUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chooseUserMouseClicked
        // TODO add your handling code here:
         if (tableUser.getSelectedRow() == -1) {
            JOptionPane.showMessageDialog(null, "Vui lòng chọn độc giả ! ", "Lỗi", JOptionPane.ERROR_MESSAGE);
        } else {
            libraryCard.setText(tableUser.getModel().getValueAt(tableUser.getSelectedRow(), 0).toString());
        }
    }//GEN-LAST:event_chooseUserMouseClicked

    private void chooserBookMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chooserBookMouseClicked
        // TODO add your handling code here:
        if (tableBook.getSelectedRow() == -1) {
            JOptionPane.showMessageDialog(null, "Vui lòng chọn sách ! ", "Lỗi", JOptionPane.ERROR_MESSAGE);
        } else {
            bookId.setText(tableBook.getModel().getValueAt(tableBook.getSelectedRow(), 0).toString());
        }
    }//GEN-LAST:event_chooserBookMouseClicked

    private void confirmMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_confirmMouseClicked
        // TODO add your handling code here:
        
        if(libraryCard.getText().equals("")||bookId.getText().equals("")){
            mess.setText("Bạn cần nhập đầy đủ thông tin ! ");
        }
        else{
            CallCard callCard = new CallCard();
            User user = homeLibrarian.userDAO.findByLibraryCard(libraryCard.getText());
            Book book = homeLibrarian.booksDAO.findByBookId(bookId.getText());
            LocalDate borrowedDate = LocalDate.of(this.borrowedDate.getDate().getYear()+1900,this.borrowedDate.getDate().getMonth()+1,this.borrowedDate.getDate().getDate());
            callCard.setBook(book);
            callCard.setUser(user);
            callCard.setBorrowedDate(borrowedDate);
            homeLibrarian.callCardDAO.save(callCard);
            homeLibrarian.resetTableCallCard();
        }
    }//GEN-LAST:event_confirmMouseClicked

    
        public void resetTableBooks(FilterForm filterForm) {
        bookList = homeLibrarian.booksDAO.findAll(filterForm);
        DefaultTableModel tbBooks = (DefaultTableModel) this.tableBook.getModel();
        tbBooks.setRowCount(0);
        for (Book book : bookList) {
            tbBooks.addRow(new Object[]{book.getBookId(), book.getName(), book.getPublisher(), book.getYearOfPublisher()});
        }
    }

    public void resetTableUsers(FilterForm filterForm) {
        userList = homeLibrarian.userDAO.findAll(filterForm);
        DefaultTableModel tableUser = (DefaultTableModel) this.tableUser.getModel();
        tableUser.setRowCount(0);
        for (User user : userList) {
            tableUser.addRow(new Object[]{user.getLibraryCard(), user.getFullname(), user.getGender(), user.getAddress()});
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreateCallCard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreateCallCard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreateCallCard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreateCallCard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CreateCallCard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField bookId;
    private com.toedter.calendar.JDateChooser borrowedDate;
    private javax.swing.JButton chooseUser;
    private javax.swing.JButton chooserBook;
    private javax.swing.JButton confirm;
    private javax.swing.JButton exit;
    private javax.swing.JTextField inputSearchBook;
    private javax.swing.JTextField inputSearchUser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField libraryCard;
    private javax.swing.JLabel mess;
    private javax.swing.JButton searchBookBtn;
    private javax.swing.JButton sreachUserBtn;
    private javax.swing.JTable tableBook;
    private javax.swing.JTable tableUser;
    // End of variables declaration//GEN-END:variables
}
