package View;

import DAO.AwaitingApprovalDAO;
import DAO.BooksDAO;
import DAO.CallCardDAO;
import DAO.ReturnBookDAO;
import DAO.UserDAO;
import Entity.AwaitingApproval;
import Entity.Book;
import Entity.CallCard;
import Entity.ReturnBook;
import Entity.User;
import Form.FilterForm;
import java.time.LocalDate;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Phong Lu Minh
 */
public class HomeLibrarian extends javax.swing.JFrame {

    /**
     * Creates new form HomeBorrower
     */
    List<Book> listBook;
    List<User> listUser;
    BooksDAO booksDAO;
    UserDAO userDAO;
    AwaitingApprovalDAO awaitingApprovalDAO;
    FilterForm filterBook;
    FilterForm filterUser;
    FilterForm filterAwait;
    CallCardDAO callCardDAO;
    List<AwaitingApproval> listAwait;
    List<CallCard> listCallCard;
    FilterForm filterCallCard;
    ReturnBookDAO returnBookDAO;

    private User user;

    public HomeLibrarian(User user) {
        this.user = user;
        initComponents();
        booksDAO = new BooksDAO();
        userDAO = new UserDAO();
        callCardDAO = new CallCardDAO();
        filterBook = new FilterForm();
        filterUser = new FilterForm();
        filterAwait = new FilterForm();
        filterCallCard = new FilterForm();
        awaitingApprovalDAO = new AwaitingApprovalDAO();
        returnBookDAO = new ReturnBookDAO();
        resetTableBooks(filterBook);
        resetTableUsers(filterUser);
        resetTableAwait();
        resetTableCallCard();
        
    }

    public HomeLibrarian() {

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        logout = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        home = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        typeSearch = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        inputSearch = new javax.swing.JTextPane();
        buttonSearch = new javax.swing.JButton();
        bookDetails = new javax.swing.JButton();
        typeSubjectFilter = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableListBook = new javax.swing.JTable();
        editBook = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        createBook = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jTabbedPane3 = new javax.swing.JTabbedPane();
        jPanel9 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane7 = new javax.swing.JScrollPane();
        tableCallCard = new javax.swing.JTable();
        inputCallCardSearch = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        isReturnBook = new javax.swing.JComboBox<>();
        statusReturnBook = new javax.swing.JComboBox<>();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jPanel10 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        tableAwait = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        typeSearchAwait = new javax.swing.JComboBox<>();
        inputSearchAwait = new javax.swing.JTextField();
        buttonSearchAwait = new javax.swing.JButton();
        confirmAwait = new javax.swing.JButton();
        deleteAwait = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tableUser = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        typeSearchUser = new javax.swing.JComboBox<>();
        inputSearchUser = new javax.swing.JTextField();
        createUser = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        editUser = new javax.swing.JButton();
        deleteUser = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 153));
        jPanel1.setPreferredSize(new java.awt.Dimension(1280, 700));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 51, 0));
        jLabel1.setText("Thư viện trường đại học Phenikaa");

        logout.setBackground(new java.awt.Color(204, 204, 255));
        logout.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Logout-icon.png"))); // NOI18N
        logout.setText("Đăng xuất");
        logout.setToolTipText("");
        logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutMouseClicked(evt);
            }
        });
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });

        jTabbedPane1.setBackground(new java.awt.Color(202, 202, 251));
        jTabbedPane1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTabbedPane1.setTabPlacement(javax.swing.JTabbedPane.LEFT);
        jTabbedPane1.setToolTipText("");
        jTabbedPane1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jTabbedPane1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jTabbedPane1.setOpaque(true);

        jPanel7.setBackground(new java.awt.Color(0, 153, 153));

        jTabbedPane2.setBackground(new java.awt.Color(0, 204, 204));
        jTabbedPane2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(102, 51, 255), null, null));
        jTabbedPane2.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N

        jTextArea2.setBackground(new java.awt.Color(255, 204, 204));
        jTextArea2.setColumns(20);
        jTextArea2.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jTextArea2.setLineWrap(true);
        jTextArea2.setRows(5);
        jTextArea2.setText("Trung tâm Thông tin Thư viện Trường Đại học Phenikaa chính thức được thành lập từ ngày 18/9/2020 theo Quyết định số 18/QĐ-ĐHP-HĐT trên cơ sở tách bộ phận Quản lý Thư viện từ Phòng Đào tạo và Quản lý sinh viên.\n\nChức năng nhiệm vụ của Trung tâm Thông tin Thư viện được quy định tại Quy định chức năng nhiệm vụ Phòng/Ban/Khoa/Viện/Trung tâm trực thuộc Trường Đại học Phenikaa.\n\nTRUNG TÂM THÔNG TIN THƯ VIỆN PHENIKAA UNI là nơi Hỗ trợ học tập / nghiên cứu / đổi mới / khởi nghiệp (Learn - Study / Research / Innovate / StartUp); Phát sinh ý tưởng mới (Ideas); Giao lưu, hợp tác, kết nối, chia sẻ học thuật (Collaborate – Connect - Sharing); Là nơi truyền cảm hứng nghiên cứu, sáng tạo (Inspire, Create).\n\nTrung tâm Thông tin - Thư viện ứng dụng và triển khai phần mềm quản trị thư viện điện tử Koha, Thư viện số Dspace, Cổng thông tin Thư viện, áp dụng các tiêu chuẩn quốc tế về mô tả biên mục AACR2, DublinCore, khung phân loại DDC, để nâng cao hiệu quả hoạt động thông tin thư viện, kết nối, hợp tác, chia sẻ tài nguyên với các Trung tâm Thông tin – Thư viện của các trường đại học trong nước và các cơ sở dữ liệu quốc tế.\n\nHơn 40.000 tài liệu in và ~4000 tài liệu số - 7 cơ sở dữ liệu khoa học trực tuyến và các nguồn học liệu mở - Hoạt động lưu thông tài liệu trên nền tảng PC và Mobile với kết nối nhanh, giao diện thân thiện, dễ sử dụng.\n\nKhông gian đọc sách mở với tổng diện tích gần 3.200m2 được thiết kế dọc các dãy hành lang chính thuộc 2 dãy tòa nhà chẵn - lẻ.\n\nĐịa điểm: Phòng 102-105 A4 (PULIC mới T4,5,6 Tòa A10)\nPhòng đọc của Trung tâm Thông tin Thư viện bạn đọc sẽ được tự do khám phá, trải nghiệm tìm kiếm kho sách theo các ngành khoa học, các lĩnh vực nghiên cứu, học tập, giải trí. Bạn đọc được trang bị các thiết bị tra cứu trực tuyến, các phần mềm thư viện điện tử, thư viện số hoạt động trên các thiết bị di động thông minh để tối ưu hóa trải nghiệm tìm kiếm khai thác sách in và đọc tài liệu số trực tuyến.\n\nKhông gian đọc sách, nghiên cứu, học tập không bị gò bó trong các phòng đọc, bạn đọc có thể mượn tài liệu và mang tài liệu tới Không gian mở để đọc một cách thoải mái với không gian tràn ngập ánh sáng, hòa mình cũng thiên nhiên cây lá cũng như không bị giới hạn về thời gian.\n\nGiờ mở cửa:\n            - Phòng đọc: Từ Thứ 2 – Thứ 6; sáng 8h-12h; chiều từ 13h-17h\n\n            - Phòng tự học: P204.A4 mở cửa 24/7\n\nCác đường link truy cập:\n            + Cổng thông tin thư viện: http://library.phenikaa-uni.edu.vn\n\n            + Thư viện điện tử: http://elib.phenikaa-uni.edu.vn\n\n            + Thư viện số: http://dlib.phenikaa-uni.edu.vn\n\nMột số liên kết quan trọng bạn đọc không thể bỏ qua:\n            + Nội quy thư viện: https://library.phenikaa-uni.edu.vn/node/156\n\n           + Một số khoản thu tại Trung tâm Thông tin Thư viện: https://library.phenikaa-uni.edu.vn/node/157\n\n            + Hướng dẫn sử dụng Thư viện: https://library.phenikaa-uni.edu.vn/node/191");
        jTextArea2.setWrapStyleWord(true);
        jTextArea2.setMargin(new java.awt.Insets(20, 20, 20, 20));
        jScrollPane4.setViewportView(jTextArea2);

        jTabbedPane2.addTab("Giới thiệu", jScrollPane4);

        jTextArea1.setBackground(new java.awt.Color(153, 255, 204));
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jTextArea1.setText("                                                                                       NỘI QUY TRUNG TÂM THÔNG TIN - THƯ VIỆN\n\n                                                                                                      TRƯỜNG ĐẠI HỌC PHENIKAA\n\n(Ban hành kèm theo Quyết định số 07/QĐ-ĐHP-TTTV ngày 05 tháng 01 năm 2021)\n\n Điều 1. Đối tượng sử dụng\n\n- Cán bộ, giảng viên, sinh viên, học viên các hệ đào tạo của Trường Đại học Phenikaa (sau đây gọi tắt là “Nhà trường”).\n\n- Đối tượng thuộc diện liên kết của Trung tâm Thông tin - Thư viện Trường Đại học Phenikaa (sau đây viết tắt là “Trung tâm TTTV”): Bạn đọc không thuộc Nhà trường, có nhu cầu sử dụng sản phẩm, dịch vụ của Trung tâm Thông tin - Thư viện phải có Giấy giới thiêụ của cơ quan chủ quản, kèm theo Chứng minh thư nhân dân/Căn cước công dân, lệ phí ký cược và phí dịch vụ theo quy định của Trung tâm TTTV.\n\n- Người sử dụng được cấp quyền sử dụng sản phẩm, dịch vụ của Trung tâm TTTV khi có đủ các điều kiện sau:\n\n          + Có tài khoản cán bộ, giảng viên, sinh viên, học viên của Trường hoặc thẻ sử dụng Thư viện đối với người sử dụng diện liên kết của Trung tâm Thông tin -Thư viện\n\n          + Tham gia và hoàn thành các lớp tập huấn sử dụng Thư viện và nộp kinh phí đặt cọc sử dụng sản phẩm, dịch vụ của Trung tâm TTTV (không áp dụng đối với cán bộ, giảng viên của Trường).\n\n          Điều 2. Trách nhiệm của người sử dụng sản phẩm, dịch vụ của Trung tâm Thông tin - Thư viện\n\n          - Không sử dụng thẻ/tài khoản của người khác và không cho người khác mượn thẻ/tài khoản. Khi mất thẻ, quên mật khẩu, phải báo ngay cho Trung tâm Thông tin - Thư viện để làm thủ tục bảo mật và được hỗ trợ.\n\n          - Xuất trình thẻ và gửi đồ vào nơi quy định; Tự bảo quản tư trang và các vật dụng cá nhân có giá trị khác.\n\n          - Chấp hành các quy định của Thư viện về việc sử dụng tài liệu, cơ sở vật chất, trang thiết bị của Thư viện.\n\n          - Giữ gìn, bảo quản tài nguyên thông tin, trang thiết bị, cơ sở vật chất của Trung tâm Thông tin - Thư viện trong quá trình sử dụng.\n\n          - Giữ trật tự, an ninh, an toàn cháy nổ và vệ sinh môi trường: không hút thuốc, không mang những vật dụng dễ cháy, nổ và đồ ăn uống (ngoài nước uống đóng chai) vào Trung tâm Thông tin – Thư viện.\n\n          - Chụp ảnh, quay phim trong khuôn viên Trung tâm Thông tin - Thư viện phải được sự đồng ý của Nhà trường.\n\n          - Xuất trình thẻ, các tài liệu, túi xách và các vật dụng khác khi có yêu cầu kiểm tra của cán bộ Thư viện.\n\n          - Tự bảo vệ thông tin cá nhân, tài khoản và mật khẩu được cấp từ Nhà trường.\n\n          - Trả lại các tài liệu chưa làm thủ tục mượn trước khi rời khỏi Trung tâm Thông tin -Thư viện.\n\n          Điều 3. Sử dụng tài liệu thư viện\n\nThời hạn mượn tài liệu tuỳ thuộc vào từng đối tượng bạn đọc và từng loại tài liệu. Hết thời hạn, nếu muốn mượn tiếp bạn đọc phải mang tài liệu đến xin gia hạn và chỉ được mượn tài liệu mới khi đã trả tài liệu cũ.\n\n1. Đối với bạn đọc là sinh viên, học viên:\n\nNgười sử dụng được mượn về nhà tối đa 05 tài liệu/1 lần, trong đó:\n\n      - Đối với các giáo trình: số lượng tối đa 10 cuốn, được mượn 150 ngày/ tài liệu và không được phép gia hạn.\n\n      - Đối với tài liệu tham khảo chuyên ngành: số lượng tối đa 05 cuốn, được mượn tối đa 90 ngày/tài liệu và được gia hạn tối đa 02 lần mỗi lần 03 ngày.\n\n      - Đối với tạp chí chuyên ngành: được mượn 14 ngày/ tài liệu và không được phép gia hạn.\n\n      - Đối với sách tham khảo: số lượng tối đa mượn là 03 cuốn, được mượn 15 ngày và không được phép gia hạn.\n\n      - Đối với tài liệu có dán 01 dấu đỏ (tài liệu nội sinh, tài liệu quý hiếm, tài liệu tra cứu, …), báo – tạp chí khác: không được mượn về nhà.\n\n          2. Đối với cán bộ, giảng viên:     \n\n      - Đối với các giáo trình: số lượng tối đa 10 cuốn, được mượn không giới hạn thời gian đối với giáo trình thuộc bộ môn giảng dạy.\n\n      - Đối với tài liệu tham khảo chuyên ngành: số lượng tối đa 05 cuốn, được mượn không giới hạn thời gian đối với giáo trình thuộc bộ môn giảng dạy.\n\n      - Đối với tạp chí chuyên ngành: được mượn 14 ngày/ tài liệu và không được phép gia hạn.\n\n      - Đối với sách tham khảo: số lượng tối đa mượn là 03 cuốn, được mượn 15 ngày và không được phép gia hạn.\n\n      - Đối với tài liệu có dán 01 dấu đỏ (tài liệu nội sinh, tài liệu quý hiếm, tài liệu tra cứu, tài liệu độc bản …), báo – tạp chí khác: không được mượn về nhà.\n\n      3. Đối với nghiên cứu viên:\n\n      - Đối với các giáo trình: số lượng tối đa 05 cuốn, được mượn 150 ngày/ tài liệu và không được phép gia hạn.\n\n      - Đối với tài liệu tham khảo chuyên ngành: số lượng tối đa 05 cuốn, được mượn tối đa 90 ngày/tài liệu và được gia hạn tối đa 02 lần mỗi lần 03 ngày.\n\n      - Đối với tạp chí chuyên ngành: được mượn 14 ngày/ tài liệu và không được phép gia hạn.\n\n      - Đối với sách tham khảo: số lượng tối đa mượn là 03 cuốn, được mượn 15 ngày và không được phép gia hạn.\n\n      - Đối với tài liệu có dán 01 dấu đỏ (tài liệu nội sinh, tài liệu quý hiếm, tài liệu tra cứu, …), báo – tạp chí khác: không được mượn về nhà.\n\n      4. Với các bạn đọc không thuộc các đối tượng trên:\n\n      - Áp dụng chính sách lưu thông tối thiểu quy định trên Phần mềm quản lý Thư viện:\n\n      - Số lượng mượn tối đa với các tài liệu (trừ tài liệu thuộc tài liệu không cho mượn: 03 cuốn\n\n      - Thời gian mượn tối đa 15 ngày, không được phép gia hạn.\n\n          Điều 4. Đối với phòng đọc sách, luận văn/ kho mở\n\nTrung tâm Thông tin - Thư viện có những không gian mở dành cho bạn đọc, bạn đọc được sử dụng mọi không gian mở trong thư viện để đọc tài liệu.\n\n          Bạn đọc tự chọn tài liệu trên giá sách, theo bảng chỉ dẫn chuyên ngành, không tráo đổi vị trí tài liệu. Bạn đọc được lấy không quá 02 cuốn cho 1 lần sử dụng.\n\n          Bạn đọc mang tài liệu qua quầy thủ thư để ghi mượn tài liệu (Áp dụng cho ghi mượn đọc tại chỗ và ghi mượn về nhà).\n\n          Đọc xong, bạn đọc chuyển tài liệu qua quầy Thủ thư để ghi trả và xếp tài liệu về vị trí quy định tại phòng đọc theo hướng dẫn của Thủ thư.\n\n          Điều 5. Đối với tra cứu tìm tin\n\n          Thư viện có hệ thống danh mục và máy tính cho bạn đọc tra cứu tìm tin. Máy tính dùng cho tra cứu tìm tin, bạn đọc không được sử dụng vào việc cá nhân khác ngoài việc tìm tin. Nghiêm cấm mọi hành vi can thiệp cá nhân vào cài đặt máy tính, gây thiệt hại đến hệ thống tra cứu của thư viện.\n\n          Điều 6. Đối với đọc báo, tạp chí\n\n          Bạn đọc tự tìm báo, tạp chí tham khảo ở trên giá, mỗi lần lấy báo, tạp chí ra bàn đọc, bạn đọc không được lấy quá 3 tên báo, hay tạp chí. Không được mang tài liệu ra ngoài phòng, bạn đọc có nhu cầu sao chép tài liệu, đăng ký với thủ thư để được phục vụ đảm bảo đúng Luật Sở hữu trí tuệ.\n\n          Điều 7. Đối với việc sao chép tài liệu\n\n          Tuyệt đối không sử dụng máy tính, điện thoại hay máy chụp ảnh để sao chép, chụp ảnh tài liệu khi chưa được phép. Nếu có nhu cầu sao chép tài liệu, bạn đọc đăng ký với thủ thư để được phục vụ đảm bảo đúng Luật Sở hữu trí tuệ.\n\n          Điều 8. Đối với việc truy cập Internet - Dữ liệu điện tử\n\n          Chỉ được sử dụng máy tính để khai thác, tìm kiếm thông tin phục vụ cho mục đích học tập và nghiên cứu khoa học. Không vào những trang Web có nội dung không lành mạnh. Khi cần sao chép dữ liệu điện tử, bạn đọc liên hệ với cán bộ thư viện để được phục vụ.\n\n          Điều 9. Thủ tục mượn sách\n\n          - Bạn đọc phải xuất trình thẻ sinh viên/tài khoản bạn đọc cho Thủ thư trước khi mượn tài liệu.\n\n          - Mượn trực tiếp: Bạn đọc chọn tài liệu và tiến hành ghi mượn với Thủ thư tại quầy.\n\n          - Mượn trực tuyến: Bạn đọc đặt mượn tài liệu trực tuyến, đến Trung tâm Thông tin – Thư viện nhận sách theo thông tin đã nhận được trên Tài khoản bạn đọc.\n\n          - Kiểm tra số lượng và tình trạng tài liệu trước khi rời khỏi Trung tâm Thông tin – Thư viện.\n\n          Điều 10. Các hình thức xử lý vi phạm nội quy\n\n          Người sử dụng vi phạm các quy định trong Nội quy này, tùy theo trường hợp, tính chất, mức độ vi phạm mà áp dụng những hình thức xử lý như sau:\n\n          - Khóa tài khoản tạm thời hoặc đình chỉ quyền sử dụng các sản phẩm, dịch vụ của Trung tâm TTTV.\n\n          - Xử phạt hành chính.\n\n          - Bồi thường thiệt hại bằng hiện vật hoặc bằng tiền.\n\n          - Mức phạt và bồi thường bằng tiền đối với các trường hợp cụ thể được thực hiện theo quy định của Nhà trường.\n\n          - Trong trường hợp vi phạm nghiêm trọng, người vi phạm có thể bị kỷ luật và truy cứu trách nhiệm hình sự theo quy định của pháp luật.\n\n          Điều 11. Bảo quản tài liệu, tài sản, khen thưởng, kỷ luật\n\n          - Tuyệt đối không mang tài liệu ra khỏi phòng đọc khi chưa được phép của cán bộ thư viện. Không tráo đổi, cắt xén, đánh dấu làm rách nát, hư hỏng tài liệu; không viết nháp hoặc ghi chép vào các trang sách, báo, tạp chí và các tài liệu khác.\n\n          - Không được sao chụp trái phép các tài liệu của thư viện. Khi sử dụng máy tính tra cứu, danh mục ... phải thực hiện đúng hướng dẫn. Nghiêm cấm mọi hành vi gây thiệt hại đến vốn tài liệu, tài sản và cơ sở vật chất của thư viện.\n\n          - Bạn đọc phải nghiêm chỉnh chấp hành những quy định trên đây. Mọi vi phạm, tuỳ theo mức độ sẽ chịu xử lý theo các hình thức kỷ luật sau:\n\n          + Nhắc nhở, cảnh cáo\n\n          + Đình chỉ quyền sử dụng thư viện từ 10 ngày đến vĩnh viễn.\n\n          + Bồi thường thiệt hại. Mức bồi thường do Nhà trường xem xét quyết định.\n\n          + Đề nghị nhà trường có hình thức xử lý kỷ luật.\n\n          + Đề nghị truy tố trước pháp luật.\n\n          - Hoan nghênh và ưu tiên phục vụ bạn đọc thực hiện tốt nội quy của Trung tâm TTTV và phát hiện những vi phạm của bạn đọc khác.\n\n          - Khi có ý kiến đóng góp về tình hình tài liệu hoặc tác phong làm việc của cán bộ thư viện, các ý kiến của bạn đọc xin gửi vào: \"Hòm thư góp ý\" tại Trung tâm TTTV, hay hộp thư điện tử: library@phenikaa-uni.edu.vn (Chú ý: Thư góp ý cần ghi rõ Họ tên, đơn vị, lớp. Mọi thư nặc danh coi như không có giá trị).\n\n          - Các trường hợp khen thưởng:\n\n          + Người sử dụng có lượt sử dụng Thư viện nhiều nhất.\n\n          + Người sử dụng tham gia tích cực vào các hoạt động của Thư viện.\n\n          + Các hình thức khen thưởng: tuyên dương, tặng quà.");
        jTextArea1.setWrapStyleWord(true);
        jTextArea1.setMargin(new java.awt.Insets(20, 20, 20, 20));
        jScrollPane3.setViewportView(jTextArea1);

        jTabbedPane2.addTab("Nội quy thư viện", jScrollPane3);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 1009, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 619, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout homeLayout = new javax.swing.GroupLayout(home);
        home.setLayout(homeLayout);
        homeLayout.setHorizontalGroup(
            homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        homeLayout.setVerticalGroup(
            homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Trang chủ", new javax.swing.ImageIcon(getClass().getResource("/Images/home.png")), home); // NOI18N

        jPanel2.setBackground(new java.awt.Color(255, 204, 204));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Tìm kiếm theo");

        typeSearch.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        typeSearch.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tất cả", "Tên Sách", "Tên Tác Giả" }));
        typeSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                typeSearchActionPerformed(evt);
            }
        });

        inputSearch.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        inputSearch.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jScrollPane1.setViewportView(inputSearch);

        buttonSearch.setBackground(new java.awt.Color(204, 255, 255));
        buttonSearch.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        buttonSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/search-icon.png"))); // NOI18N
        buttonSearch.setText("Tìm kiếm");
        buttonSearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonSearchMouseClicked(evt);
            }
        });

        bookDetails.setBackground(new java.awt.Color(204, 255, 204));
        bookDetails.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bookDetails.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/infor-icon.png"))); // NOI18N
        bookDetails.setText("Xem chi tiết");
        bookDetails.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bookDetailsMouseClicked(evt);
            }
        });
        bookDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookDetailsActionPerformed(evt);
            }
        });

        typeSubjectFilter.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        typeSubjectFilter.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tất cả", "Sách Chính trị – pháp luật", "Sách Khoa học công nghệ – Kinh tế", "Sách Văn học nghệ thuật", "Sách Văn hóa xã hội – Lịch sử", "Sách Giáo trình", "Sách Truyện, tiểu thuyết", "Sách Tâm lý, tâm linh, tôn giáo", "Sách thiếu nhi" }));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Thể loại");

        tableListBook.setAutoCreateRowSorter(true);
        tableListBook.setBackground(new java.awt.Color(254, 232, 250));
        tableListBook.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        tableListBook.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã sách", "Tên sách", "Nhà xuất bản", "Năm xuất bản", "Tác giả", "Thể loại", "Số sách còn lại"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableListBook.setToolTipText("");
        tableListBook.setIntercellSpacing(new java.awt.Dimension(5, 5));
        tableListBook.setRowHeight(30);
        tableListBook.setShowGrid(true);
        jScrollPane2.setViewportView(tableListBook);

        editBook.setBackground(new java.awt.Color(255, 255, 51));
        editBook.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        editBook.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/edit-icon.png"))); // NOI18N
        editBook.setText("Sửa");
        editBook.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editBookMouseClicked(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(255, 0, 0));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/delete-icon.png"))); // NOI18N
        jButton2.setText("Xóa");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        createBook.setBackground(new java.awt.Color(51, 255, 51));
        createBook.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        createBook.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/plus-icon.png"))); // NOI18N
        createBook.setText("Thêm");
        createBook.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                createBookMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(typeSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(typeSubjectFilter, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(bookDetails)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(createBook)
                        .addGap(18, 18, 18)
                        .addComponent(editBook)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jButton2))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(buttonSearch)))
                .addContainerGap(109, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane2)
                    .addContainerGap()))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane1)
                        .addComponent(buttonSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(typeSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bookDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(typeSubjectFilter, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(createBook, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editBook, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(525, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                    .addGap(103, 103, 103)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 510, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Quản lý sách", new javax.swing.ImageIcon(getClass().getResource("/Images/book.png")), jPanel3); // NOI18N

        jTabbedPane3.setBackground(new java.awt.Color(255, 204, 255));
        jTabbedPane3.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jTabbedPane3.setOpaque(true);

        jPanel6.setBackground(new java.awt.Color(246, 238, 238));

        tableCallCard.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        tableCallCard.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã Mượn Sách", "Thẻ Thư Viện", "Người Mượn", "Mã Sách", "Tên Sách", "Ngày Mượn", "Số Ngày Mượn", "Ngày Trả", "Tình Trạng Sách", "Tiền Phạt", "Ghi Chú"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Long.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tableCallCard.setIntercellSpacing(new java.awt.Dimension(5, 5));
        tableCallCard.setRowHeight(30);
        jScrollPane7.setViewportView(tableCallCard);

        inputCallCardSearch.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N

        jButton1.setBackground(new java.awt.Color(204, 255, 255));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/search-icon.png"))); // NOI18N
        jButton1.setText("Tìm kiếm");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Tình trạng sách");

        isReturnBook.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        isReturnBook.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tất cả", "Chưa trả", "Đã trả" }));
        isReturnBook.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                isReturnBookItemStateChanged(evt);
            }
        });
        isReturnBook.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                isReturnBookPropertyChange(evt);
            }
        });

        statusReturnBook.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tất cả", "Bình thường", "Hư hỏng", "Làm mất" }));
        statusReturnBook.setEnabled(false);

        jButton4.setBackground(new java.awt.Color(255, 204, 255));
        jButton4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/create-icon.png"))); // NOI18N
        jButton4.setText("Tạo Phiếu Mượn");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(153, 255, 255));
        jButton5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/return-book.png"))); // NOI18N
        jButton5.setText("Trả sách");
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton5MouseClicked(evt);
            }
        });

        jButton6.setBackground(new java.awt.Color(204, 255, 204));
        jButton6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/infor-icon.png"))); // NOI18N
        jButton6.setText("Xem Chi Tiết");
        jButton6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton6MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 989, Short.MAX_VALUE)
                        .addGap(14, 14, 14))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(inputCallCardSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton1)
                                .addGap(18, 18, 18)
                                .addComponent(jButton6)
                                .addGap(18, 18, 18)
                                .addComponent(jButton4)
                                .addGap(18, 18, 18)
                                .addComponent(jButton5))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(isReturnBook, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(statusReturnBook, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(107, Short.MAX_VALUE))))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputCallCardSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(isReturnBook, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(statusReturnBook, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 495, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTabbedPane3.addTab("Phiếu mượn", jPanel9);

        jPanel11.setBackground(new java.awt.Color(236, 255, 245));

        tableAwait.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        tableAwait.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Người Mượn", "Thẻ Thư Viện", "Mã Sách", "Tên Sách", "Nhà Xuất Bản", "Năm Xuất Bản", "Tác Giả", "Giá Tiền", "Số ngày mượn"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableAwait.setIntercellSpacing(new java.awt.Dimension(5, 5));
        tableAwait.setRowHeight(30);
        jScrollPane6.setViewportView(tableAwait);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel5.setText("Tìm kiếm theo");

        typeSearchAwait.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tên Độc Giả", "Thẻ Thư Viện" }));

        buttonSearchAwait.setBackground(new java.awt.Color(0, 255, 204));
        buttonSearchAwait.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        buttonSearchAwait.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/search-icon.png"))); // NOI18N
        buttonSearchAwait.setText("Tìm kiếm");
        buttonSearchAwait.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonSearchAwaitMouseClicked(evt);
            }
        });

        confirmAwait.setBackground(new java.awt.Color(0, 255, 0));
        confirmAwait.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        confirmAwait.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/confirm-icon.png"))); // NOI18N
        confirmAwait.setText("Duyệt");
        confirmAwait.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                confirmAwaitMouseClicked(evt);
            }
        });

        deleteAwait.setBackground(new java.awt.Color(255, 51, 51));
        deleteAwait.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        deleteAwait.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/delete-icon.png"))); // NOI18N
        deleteAwait.setText("Xóa");
        deleteAwait.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deleteAwaitMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane6)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(typeSearchAwait, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(inputSearchAwait, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(buttonSearchAwait)
                        .addGap(18, 18, 18)
                        .addComponent(confirmAwait)
                        .addGap(18, 18, 18)
                        .addComponent(deleteAwait)
                        .addGap(0, 114, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(typeSearchAwait, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(inputSearchAwait, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(confirmAwait, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(deleteAwait, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(buttonSearchAwait, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 504, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTabbedPane3.addTab("Danh sách chờ mượn", jPanel10);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane3)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane3)
        );

        jTabbedPane1.addTab("Quản lý phiếu mượn", new javax.swing.ImageIcon(getClass().getResource("/Images/callCard-icon.png")), jPanel5); // NOI18N

        jPanel8.setBackground(new java.awt.Color(211, 255, 255));

        tableUser.setAutoCreateRowSorter(true);
        tableUser.setBackground(new java.awt.Color(235, 255, 235));
        tableUser.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        tableUser.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Thẻ thư viện", "Họ và tên", "Giới tính", "Quê quán", "Ngày sinh", "Số điện thoại", "Số sách đang mượn", "Số sách đã mượn"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableUser.setIntercellSpacing(new java.awt.Dimension(5, 5));
        tableUser.setRowHeight(30);
        tableUser.setShowGrid(true);
        jScrollPane5.setViewportView(tableUser);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        jLabel4.setText("Tìm kiếm theo");

        typeSearchUser.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        typeSearchUser.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Họ và tên", "Thẻ thư viện" }));

        createUser.setBackground(new java.awt.Color(0, 255, 0));
        createUser.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        createUser.setText("Tạo tài khoản");
        createUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                createUserMouseClicked(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(255, 204, 255));
        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/search-user-icon.png"))); // NOI18N
        jButton3.setText("Tìm kiếm");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });

        editUser.setBackground(new java.awt.Color(255, 255, 51));
        editUser.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        editUser.setText("Sửa");
        editUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editUserMouseClicked(evt);
            }
        });

        deleteUser.setBackground(new java.awt.Color(255, 0, 51));
        deleteUser.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        deleteUser.setText("Xóa");
        deleteUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deleteUserMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 982, Short.MAX_VALUE)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(typeSearchUser, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(inputSearchUser, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(createUser)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(editUser)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(deleteUser)))
                .addGap(15, 15, 15))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(typeSearchUser, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inputSearchUser, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(createUser, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editUser, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deleteUser, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 535, Short.MAX_VALUE)
                .addGap(17, 17, 17))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Quản lý độc giả", new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-library-30.png")), jPanel4); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 809, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(139, 139, 139)
                .addComponent(logout)
                .addContainerGap())
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1280, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(logout, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addComponent(jTabbedPane1))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseClicked
        Login login = new Login();
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_logoutMouseClicked

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_logoutActionPerformed

    private void bookDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookDetailsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bookDetailsActionPerformed

    private void bookDetailsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bookDetailsMouseClicked
        // TODO add your handling code here:

        if (tableListBook.getSelectedRow() == -1) {
            JOptionPane.showMessageDialog(null, "Vui lòng chọn sách để xem chi tiết", "Lỗi", JOptionPane.ERROR_MESSAGE);
        } else {
            BooksDAO booksDAO = new BooksDAO();
            String bookId = tableListBook.getModel().getValueAt(tableListBook.getSelectedRow(), 0).toString();
            Book book = booksDAO.findByBookId(bookId);
            BookDetails bookDetails = new BookDetails(book);
            bookDetails.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
            bookDetails.setVisible(true);

        }
    }//GEN-LAST:event_bookDetailsMouseClicked

    private void buttonSearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonSearchMouseClicked
        // TODO add your handling code here:
        if (!typeSubjectFilter.getSelectedItem().equals("Tất cả")) {
            filterBook.setTypeFilter("subject");
            filterBook.setFilter(typeSubjectFilter.getSelectedItem().toString());
        }
        if (typeSubjectFilter.getSelectedItem().equals("Tất cả")) {
            filterBook.setTypeFilter("");
            filterBook.setFilter("");
        }
        switch (typeSearch.getSelectedItem().toString()) {
            case "Tất cả":
                filterBook.setTypeSearch("`name` LIKE '%" + inputSearch.getText() + "%' OR `author`");
                filterBook.setSearch(inputSearch.getText());
                break;
            case "Tên Sách":
                filterBook.setTypeSearch("name");
                filterBook.setSearch(inputSearch.getText());
                break;
            case "Tên Tác Giả":
                filterBook.setTypeSearch("author");
                filterBook.setSearch(inputSearch.getText());
                break;
            default:
                break;
        }
        resetTableBooks(filterBook);

    }//GEN-LAST:event_buttonSearchMouseClicked

    private void typeSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_typeSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_typeSearchActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        // TODO add your handling code here:

        switch (typeSearchUser.getSelectedItem().toString()) {
            case "Họ và tên":
                filterUser.setTypeSearch("fullname");
                filterUser.setSearch(inputSearchUser.getText());
                break;
            case "Thẻ thư viện":
                filterUser.setTypeSearch("libraryCard");
                filterUser.setSearch(inputSearchUser.getText());
                break;
            default:
                break;
        }
        resetTableUsers(filterUser);
    }//GEN-LAST:event_jButton3MouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
        if (tableListBook.getSelectedRow() == -1) {
            JOptionPane.showMessageDialog(null, "Vui lòng chọn sách để xóa ! ", "Lỗi", JOptionPane.ERROR_MESSAGE);
        } else {
            String bookId = tableListBook.getModel().getValueAt(tableListBook.getSelectedRow(), 0).toString();
            String bookName = tableListBook.getModel().getValueAt(tableListBook.getSelectedRow(), 1).toString();
            if (JOptionPane.showConfirmDialog(this, "Bạn có chắc chắn muốn xóa sách " + bookName, "Xóa sách", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
                booksDAO.delete(bookId);
                resetTableBooks(filterBook);
            }
        }
    }//GEN-LAST:event_jButton2MouseClicked

    private void createBookMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_createBookMouseClicked
        // TODO add your handling code here:
        CreateBook createBook = new CreateBook(this);
        createBook.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        createBook.setVisible(true);


    }//GEN-LAST:event_createBookMouseClicked

    private void editBookMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editBookMouseClicked
        // TODO add your handling code here:
        if (tableListBook.getSelectedRow() == -1) {
            JOptionPane.showMessageDialog(null, "Vui lòng chọn sách để cập nhật !", "Lỗi", JOptionPane.ERROR_MESSAGE);
        } else {
            String bookId = tableListBook.getModel().getValueAt(tableListBook.getSelectedRow(), 0).toString();
            Book book = booksDAO.findByBookId(bookId);
            EditBook editBook = new EditBook(book, this);
            editBook.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
            editBook.setVisible(true);
        }
    }//GEN-LAST:event_editBookMouseClicked

    private void buttonSearchAwaitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonSearchAwaitMouseClicked
        // TODO add your handling code here:
        if (!inputSearchAwait.getText().equals("")) {
            filterAwait.setTypeSearch(typeSearchAwait.getSelectedItem().toString());
            filterAwait.setSearch(inputSearchAwait.getText());
        }
        resetTableAwait();
    }//GEN-LAST:event_buttonSearchAwaitMouseClicked

    private void deleteAwaitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteAwaitMouseClicked
        // TODO add your handling code here:
        if (tableAwait.getSelectedRow() == -1) {
            JOptionPane.showMessageDialog(null, "Vui lòng chọn yêu cầu để xóa ! ", "Lỗi", JOptionPane.ERROR_MESSAGE);
        } else {
            int[] rows = tableAwait.getSelectedRows();
            for (int i : rows) {
                int awaitId = Integer.parseInt(tableAwait.getModel().getValueAt(i, 0).toString());
                awaitingApprovalDAO.deleteById(awaitId);
            }
            resetTableAwait();
        }
    }//GEN-LAST:event_deleteAwaitMouseClicked

    private void confirmAwaitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_confirmAwaitMouseClicked
        // TODO add your handling code here:
         if (tableAwait.getSelectedRow() == -1) {
            JOptionPane.showMessageDialog(null, "Vui lòng chọn yêu cầu để duyệt ! ", "Lỗi", JOptionPane.ERROR_MESSAGE);
        } else {
            int[] rows = tableAwait.getSelectedRows();
            for (int i : rows) {
                User user = userDAO.findByLibraryCard(tableAwait.getModel().getValueAt(i,2).toString());
                Book book = booksDAO.findByBookId(tableAwait.getModel().getValueAt(i,3).toString());
                CallCard callCard = new CallCard();
                callCard.setUser(user);
                callCard.setBook(book);
                callCard.setBorrowedDay(Integer.parseInt(tableAwait.getModel().getValueAt(i,9).toString()));
                callCard.setBorrowedDate(LocalDate.now());
                callCardDAO.save(callCard);
            }
            for(int i:rows){
                int awaitId = Integer.parseInt(tableAwait.getModel().getValueAt(i, 0).toString());
                awaitingApprovalDAO.deleteById(awaitId);
            }
            resetTableAwait();
            resetTableCallCard();
        }
    }//GEN-LAST:event_confirmAwaitMouseClicked

    private void isReturnBookPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_isReturnBookPropertyChange

    }//GEN-LAST:event_isReturnBookPropertyChange

    private void isReturnBookItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_isReturnBookItemStateChanged
        // TODO add your handling code here:

        if(isReturnBook.getSelectedItem().toString().equals("Chưa trả")||isReturnBook.getSelectedItem().toString().equals("Tất cả")){
            statusReturnBook.setEnabled(false);
            statusReturnBook.setSelectedIndex(0);
        }
        else{
            statusReturnBook.setEnabled(true);
        }
    }//GEN-LAST:event_isReturnBookItemStateChanged

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        filterCallCard.setSearch(inputCallCardSearch.getText());
        filterCallCard.setTypeFilter(isReturnBook.getSelectedItem().toString());
        filterCallCard.setFilter(statusReturnBook.getSelectedItem().toString());
        
        resetTableCallCard();
    }//GEN-LAST:event_jButton1MouseClicked

    private void createUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_createUserMouseClicked
        // TODO add your handling code here:
        CreateUser createUser = new CreateUser(this);
        createUser.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        createUser.setVisible(true);
    }//GEN-LAST:event_createUserMouseClicked

    private void editUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editUserMouseClicked
        // TODO add your handling code here:
         if (tableUser.getSelectedRow() == -1) {
            JOptionPane.showMessageDialog(null, "Vui lòng chọn độc giả để sửa thông tin ! ", "Lỗi", JOptionPane.ERROR_MESSAGE);
        } else {
        User user = userDAO.findByLibraryCard(tableUser.getModel().getValueAt(tableUser.getSelectedRow(),0).toString());
        UpdateInforUser updateInforUser = new UpdateInforUser(user,this);
            updateInforUser.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
            updateInforUser.setVisible(true);
        }
    }//GEN-LAST:event_editUserMouseClicked

    private void deleteUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteUserMouseClicked
        // TODO add your handling code here:
         if (tableUser.getSelectedRow() == -1) {
            JOptionPane.showMessageDialog(null, "Vui lòng chọn độc giả để xóa ! ", "Lỗi", JOptionPane.ERROR_MESSAGE);
        } else {
        String libraryCard = tableUser.getModel().getValueAt(tableUser.getSelectedRow(),0).toString();
        String name = tableUser.getModel().getValueAt(tableUser.getSelectedRow(),1).toString();
       
        if (JOptionPane.showConfirmDialog(this, "Bạn có chắc chắn muốn xóa độc giả " + name, "Xóa độc giả", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
               userDAO.deleteByLibraryCard(libraryCard);
                resetTableUsers(filterBook);
            }
        
        }
    }//GEN-LAST:event_deleteUserMouseClicked

    private void jButton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseClicked
        // TODO add your handling code here:
        if (tableCallCard.getSelectedRow() == -1) {
            JOptionPane.showMessageDialog(null, "Vui lòng chọn phiếu mượn để trả sách ! ", "Lỗi", JOptionPane.ERROR_MESSAGE);
        } else {
        
            if(!tableCallCard.getModel().getValueAt(tableCallCard.getSelectedRow(),7).toString().equals("Chưa trả")){
                JOptionPane.showMessageDialog(null, "Phiếu mượn này đã được trả ! ", "Lỗi", JOptionPane.ERROR_MESSAGE);
            }
            else{
              String callCardId = tableCallCard.getModel().getValueAt(tableCallCard.getSelectedRow(),0).toString();
              CallCard callCard = callCardDAO.findByCallCardId(callCardId);

              ReturnBookView returnBookView = new ReturnBookView(callCard,this);
              returnBookView.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
              returnBookView.setVisible(true);
            }
        }
    }//GEN-LAST:event_jButton5MouseClicked

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton6MouseClicked
        // TODO add your handling code here:
        if (tableCallCard.getSelectedRow() == -1) {
            JOptionPane.showMessageDialog(null, "Vui lòng chọn phiếu mượn để xem chi tiết ! ", "Lỗi", JOptionPane.ERROR_MESSAGE);
        } else {
        
              String callCardId = tableCallCard.getModel().getValueAt(tableCallCard.getSelectedRow(),0).toString();
              CallCard callCard = callCardDAO.findByCallCardId(callCardId);
              ReturnBook returnBook = returnBookDAO.findByCallCardId(callCardId);
              CallCarDetails callCarDetails = new CallCarDetails(callCard,returnBook);
              callCarDetails.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
              callCarDetails.setVisible(true);
              
            }
    }//GEN-LAST:event_jButton6MouseClicked

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
        // TODO add your handling code here:
        CreateCallCard createCallCard = new CreateCallCard(this);
        createCallCard.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        createCallCard.setVisible(true);
    }//GEN-LAST:event_jButton4MouseClicked

    public void resetTableBooks(FilterForm filterForm) {
        listBook = booksDAO.findAll(filterForm);
        DefaultTableModel tbBooks = (DefaultTableModel) tableListBook.getModel();
        tbBooks.setRowCount(0);
        for (Book book : listBook) {
            int numberOfBook = book.getTotalQuantity()-callCardDAO.numberOfBorrowingBooksByBookId(book.getBookId());
            tbBooks.addRow(new Object[]{book.getBookId(), book.getName(), book.getPublisher(), book.getYearOfPublisher(), book.getAuthor(), book.getSubject(),numberOfBook});
        }
    }

    public void resetTableUsers(FilterForm filterForm) {
        listUser = userDAO.findAll(filterForm);
        DefaultTableModel tableUser = (DefaultTableModel) this.tableUser.getModel();
        tableUser.setRowCount(0);
        for (User user : listUser) {
            int numberOfBooksBorrowed = callCardDAO.findByLibraryCard(user.getLibraryCard()).size();
            int numberOfBooksBorrowing=callCardDAO.numberOfBorrowingBooksByUser(user.getLibraryCard());
            tableUser.addRow(new Object[]{user.getLibraryCard(), user.getFullname(), user.getGender(), user.getAddress(), user.getDateOfBirth().toString(), user.getNumberPhone(),numberOfBooksBorrowing,numberOfBooksBorrowed});
        }
    }

    public void resetTableAwait() {
        listAwait = awaitingApprovalDAO.findAll(filterAwait);
        DefaultTableModel tableAwait = (DefaultTableModel) this.tableAwait.getModel();
        tableAwait.setRowCount(0);
        for (AwaitingApproval await : listAwait) {
            tableAwait.addRow(new Object[]{await.getId(), await.getUser().getFullname(), await.getUser().getLibraryCard(), await.getBook().getBookId(),
                 await.getBook().getName(), await.getBook().getPublisher(), await.getBook().getYearOfPublisher(), await.getBook().getAuthor(),
                await.getBook().getPrice(), await.getBorrowedDay()});
        }
    }
    
    public void resetTableCallCard(){
        listCallCard = callCardDAO.findAll(filterCallCard);
        DefaultTableModel tableCallCard = (DefaultTableModel) this.tableCallCard.getModel();
        tableCallCard.setRowCount(0);
        for (CallCard callCard : listCallCard) {
            ReturnBook returnBook = returnBookDAO.findByCallCardId(callCard.getCallCardId());
            if(returnBook.getReturnBookId()==null){
                tableCallCard.addRow(new Object[]{callCard.getCallCardId(),callCard.getUser().getLibraryCard(),callCard.getUser().getLibraryCard(),
                callCard.getBook().getBookId(),callCard.getBook().getName(),callCard.getBorrowedDate(),callCard.getBorrowedDay(),"Chưa trả"});
            }
            else{
                tableCallCard.addRow(new Object[]{callCard.getCallCardId(),callCard.getUser().getLibraryCard(),callCard.getUser().getLibraryCard(),
                callCard.getBook().getBookId(),callCard.getBook().getName(),callCard.getBorrowedDate(),callCard.getBorrowedDay(),returnBook.getPayDay(),
                returnBook.getStatus(),returnBook.getFines(),returnBook.getNote()});
            }
            
            
        }
        resetTableBooks(filterBook);
        resetTableUsers(filterUser);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomeLibrarian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomeLibrarian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomeLibrarian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomeLibrarian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomeLibrarian().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bookDetails;
    private javax.swing.JButton buttonSearch;
    private javax.swing.JButton buttonSearchAwait;
    private javax.swing.JButton confirmAwait;
    private javax.swing.JButton createBook;
    private javax.swing.JButton createUser;
    private javax.swing.JButton deleteAwait;
    private javax.swing.JButton deleteUser;
    private javax.swing.JButton editBook;
    private javax.swing.JButton editUser;
    private javax.swing.JPanel home;
    private javax.swing.JTextField inputCallCardSearch;
    private javax.swing.JTextPane inputSearch;
    private javax.swing.JTextField inputSearchAwait;
    private javax.swing.JTextField inputSearchUser;
    private javax.swing.JComboBox<String> isReturnBook;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JButton logout;
    private javax.swing.JComboBox<String> statusReturnBook;
    private javax.swing.JTable tableAwait;
    private javax.swing.JTable tableCallCard;
    private javax.swing.JTable tableListBook;
    private javax.swing.JTable tableUser;
    private javax.swing.JComboBox<String> typeSearch;
    private javax.swing.JComboBox<String> typeSearchAwait;
    private javax.swing.JComboBox<String> typeSearchUser;
    private javax.swing.JComboBox<String> typeSubjectFilter;
    // End of variables declaration//GEN-END:variables
}
